import type { Metadata } from "next";
import { Inter, Syne } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ChatProvider } from "@/hooks/useChat";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ChatProvider>
    <html lang="en">
      <body className={` scroll-smooth`}>
      
        <Toaster />
  
        {children}
  
     
        </body>
  
    </html>
    </ChatProvider>
    </ClerkProvider>
  );
}